// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.4
// source: monitor/v1/monitor.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "monitor.v1";

export enum Protocol {
  PROTOCOL_UNSPECIFIED = 0,
  PROTOCOL_HTTP = 1,
  PROTOCOL_HTTP_STREAM = 2,
  PROTOCOL_GRPC = 3,
  PROTOCOL_GRPC_STREAM = 4,
  UNRECOGNIZED = -1,
}

export function protocolFromJSON(object: any): Protocol {
  switch (object) {
    case 0:
    case "PROTOCOL_UNSPECIFIED":
      return Protocol.PROTOCOL_UNSPECIFIED;
    case 1:
    case "PROTOCOL_HTTP":
      return Protocol.PROTOCOL_HTTP;
    case 2:
    case "PROTOCOL_HTTP_STREAM":
      return Protocol.PROTOCOL_HTTP_STREAM;
    case 3:
    case "PROTOCOL_GRPC":
      return Protocol.PROTOCOL_GRPC;
    case 4:
    case "PROTOCOL_GRPC_STREAM":
      return Protocol.PROTOCOL_GRPC_STREAM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Protocol.UNRECOGNIZED;
  }
}

export function protocolToJSON(object: Protocol): string {
  switch (object) {
    case Protocol.PROTOCOL_UNSPECIFIED:
      return "PROTOCOL_UNSPECIFIED";
    case Protocol.PROTOCOL_HTTP:
      return "PROTOCOL_HTTP";
    case Protocol.PROTOCOL_HTTP_STREAM:
      return "PROTOCOL_HTTP_STREAM";
    case Protocol.PROTOCOL_GRPC:
      return "PROTOCOL_GRPC";
    case Protocol.PROTOCOL_GRPC_STREAM:
      return "PROTOCOL_GRPC_STREAM";
    case Protocol.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum DeviceStatus {
  DEVICE_STATUS_UNSPECIFIED = 0,
  DEVICE_STATUS_HEALTHY = 1,
  DEVICE_STATUS_DEGRADED = 2,
  DEVICE_STATUS_ERROR = 3,
  DEVICE_STATUS_MAINTENANCE = 4,
  DEVICE_STATUS_BOOTING = 5,
  DEVICE_STATUS_OFFLINE = 6,
  UNRECOGNIZED = -1,
}

export function deviceStatusFromJSON(object: any): DeviceStatus {
  switch (object) {
    case 0:
    case "DEVICE_STATUS_UNSPECIFIED":
      return DeviceStatus.DEVICE_STATUS_UNSPECIFIED;
    case 1:
    case "DEVICE_STATUS_HEALTHY":
      return DeviceStatus.DEVICE_STATUS_HEALTHY;
    case 2:
    case "DEVICE_STATUS_DEGRADED":
      return DeviceStatus.DEVICE_STATUS_DEGRADED;
    case 3:
    case "DEVICE_STATUS_ERROR":
      return DeviceStatus.DEVICE_STATUS_ERROR;
    case 4:
    case "DEVICE_STATUS_MAINTENANCE":
      return DeviceStatus.DEVICE_STATUS_MAINTENANCE;
    case 5:
    case "DEVICE_STATUS_BOOTING":
      return DeviceStatus.DEVICE_STATUS_BOOTING;
    case 6:
    case "DEVICE_STATUS_OFFLINE":
      return DeviceStatus.DEVICE_STATUS_OFFLINE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DeviceStatus.UNRECOGNIZED;
  }
}

export function deviceStatusToJSON(object: DeviceStatus): string {
  switch (object) {
    case DeviceStatus.DEVICE_STATUS_UNSPECIFIED:
      return "DEVICE_STATUS_UNSPECIFIED";
    case DeviceStatus.DEVICE_STATUS_HEALTHY:
      return "DEVICE_STATUS_HEALTHY";
    case DeviceStatus.DEVICE_STATUS_DEGRADED:
      return "DEVICE_STATUS_DEGRADED";
    case DeviceStatus.DEVICE_STATUS_ERROR:
      return "DEVICE_STATUS_ERROR";
    case DeviceStatus.DEVICE_STATUS_MAINTENANCE:
      return "DEVICE_STATUS_MAINTENANCE";
    case DeviceStatus.DEVICE_STATUS_BOOTING:
      return "DEVICE_STATUS_BOOTING";
    case DeviceStatus.DEVICE_STATUS_OFFLINE:
      return "DEVICE_STATUS_OFFLINE";
    case DeviceStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Device {
  id: string;
  deviceId: string;
  alias: string;
  host: string;
  port: number;
  portGateway: number;
  architecture: string;
  os: string;
  supportedProtocols: Protocol[];
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface Diagnostics {
  hardwareVersion: string;
  softwareVersion: string;
  firmwareVersion: string;
  cpuUsage: number;
  memoryUsage: number;
  deviceStatus: DeviceStatus;
  checksum: string;
}

export interface RegisterDeviceRequest {
  deviceId: string;
  alias: string;
  host: string;
  port: number;
  portGateway: number;
  protocol: Protocol;
}

export interface RegisterDeviceResponse {
  device: Device | undefined;
}

export interface ListDevicesResponse {
  devices: Device[];
}

export interface UpdateDeviceRequest {
  deviceId: string;
  deviceStatus: DeviceStatus;
}

export interface DiagnosticsRequest {
  deviceId: string;
}

export interface DiagnosticsResponse {
  device: Device | undefined;
  diagnostics: Diagnostics | undefined;
  updatedAt: Date | undefined;
}

function createBaseDevice(): Device {
  return {
    id: "",
    deviceId: "",
    alias: "",
    host: "",
    port: 0,
    portGateway: 0,
    architecture: "",
    os: "",
    supportedProtocols: [],
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const Device = {
  encode(message: Device, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.deviceId !== "") {
      writer.uint32(18).string(message.deviceId);
    }
    if (message.alias !== "") {
      writer.uint32(26).string(message.alias);
    }
    if (message.host !== "") {
      writer.uint32(34).string(message.host);
    }
    if (message.port !== 0) {
      writer.uint32(40).int64(message.port);
    }
    if (message.portGateway !== 0) {
      writer.uint32(48).int64(message.portGateway);
    }
    if (message.architecture !== "") {
      writer.uint32(58).string(message.architecture);
    }
    if (message.os !== "") {
      writer.uint32(66).string(message.os);
    }
    writer.uint32(74).fork();
    for (const v of message.supportedProtocols) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(82).fork()).ldelim();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(90).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Device {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDevice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.alias = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.host = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.port = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.portGateway = longToNumber(reader.int64() as Long);
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.architecture = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.os = reader.string();
          continue;
        case 9:
          if (tag === 72) {
            message.supportedProtocols.push(reader.int32() as any);

            continue;
          }

          if (tag === 74) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.supportedProtocols.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Device {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      deviceId: isSet(object.device_id) ? globalThis.String(object.device_id) : "",
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      portGateway: isSet(object.port_gateway) ? globalThis.Number(object.port_gateway) : 0,
      architecture: isSet(object.architecture) ? globalThis.String(object.architecture) : "",
      os: isSet(object.os) ? globalThis.String(object.os) : "",
      supportedProtocols: globalThis.Array.isArray(object?.supported_protocols)
        ? object.supported_protocols.map((e: any) => protocolFromJSON(e))
        : [],
      createdAt: isSet(object.created_at) ? fromJsonTimestamp(object.created_at) : undefined,
      updatedAt: isSet(object.updated_at) ? fromJsonTimestamp(object.updated_at) : undefined,
    };
  },

  toJSON(message: Device): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.deviceId !== "") {
      obj.device_id = message.deviceId;
    }
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.portGateway !== 0) {
      obj.port_gateway = Math.round(message.portGateway);
    }
    if (message.architecture !== "") {
      obj.architecture = message.architecture;
    }
    if (message.os !== "") {
      obj.os = message.os;
    }
    if (message.supportedProtocols?.length) {
      obj.supported_protocols = message.supportedProtocols.map((e) => protocolToJSON(e));
    }
    if (message.createdAt !== undefined) {
      obj.created_at = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updated_at = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Device>, I>>(base?: I): Device {
    return Device.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Device>, I>>(object: I): Device {
    const message = createBaseDevice();
    message.id = object.id ?? "";
    message.deviceId = object.deviceId ?? "";
    message.alias = object.alias ?? "";
    message.host = object.host ?? "";
    message.port = object.port ?? 0;
    message.portGateway = object.portGateway ?? 0;
    message.architecture = object.architecture ?? "";
    message.os = object.os ?? "";
    message.supportedProtocols = object.supportedProtocols?.map((e) => e) || [];
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseDiagnostics(): Diagnostics {
  return {
    hardwareVersion: "",
    softwareVersion: "",
    firmwareVersion: "",
    cpuUsage: 0,
    memoryUsage: 0,
    deviceStatus: 0,
    checksum: "",
  };
}

export const Diagnostics = {
  encode(message: Diagnostics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.hardwareVersion !== "") {
      writer.uint32(10).string(message.hardwareVersion);
    }
    if (message.softwareVersion !== "") {
      writer.uint32(18).string(message.softwareVersion);
    }
    if (message.firmwareVersion !== "") {
      writer.uint32(26).string(message.firmwareVersion);
    }
    if (message.cpuUsage !== 0) {
      writer.uint32(33).double(message.cpuUsage);
    }
    if (message.memoryUsage !== 0) {
      writer.uint32(41).double(message.memoryUsage);
    }
    if (message.deviceStatus !== 0) {
      writer.uint32(48).int32(message.deviceStatus);
    }
    if (message.checksum !== "") {
      writer.uint32(58).string(message.checksum);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Diagnostics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiagnostics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.hardwareVersion = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.softwareVersion = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.firmwareVersion = reader.string();
          continue;
        case 4:
          if (tag !== 33) {
            break;
          }

          message.cpuUsage = reader.double();
          continue;
        case 5:
          if (tag !== 41) {
            break;
          }

          message.memoryUsage = reader.double();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.deviceStatus = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.checksum = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Diagnostics {
    return {
      hardwareVersion: isSet(object.hardware_version) ? globalThis.String(object.hardware_version) : "",
      softwareVersion: isSet(object.software_version) ? globalThis.String(object.software_version) : "",
      firmwareVersion: isSet(object.firmware_version) ? globalThis.String(object.firmware_version) : "",
      cpuUsage: isSet(object.cpu_usage) ? globalThis.Number(object.cpu_usage) : 0,
      memoryUsage: isSet(object.memory_usage) ? globalThis.Number(object.memory_usage) : 0,
      deviceStatus: isSet(object.device_status) ? deviceStatusFromJSON(object.device_status) : 0,
      checksum: isSet(object.checksum) ? globalThis.String(object.checksum) : "",
    };
  },

  toJSON(message: Diagnostics): unknown {
    const obj: any = {};
    if (message.hardwareVersion !== "") {
      obj.hardware_version = message.hardwareVersion;
    }
    if (message.softwareVersion !== "") {
      obj.software_version = message.softwareVersion;
    }
    if (message.firmwareVersion !== "") {
      obj.firmware_version = message.firmwareVersion;
    }
    if (message.cpuUsage !== 0) {
      obj.cpu_usage = message.cpuUsage;
    }
    if (message.memoryUsage !== 0) {
      obj.memory_usage = message.memoryUsage;
    }
    if (message.deviceStatus !== 0) {
      obj.device_status = deviceStatusToJSON(message.deviceStatus);
    }
    if (message.checksum !== "") {
      obj.checksum = message.checksum;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Diagnostics>, I>>(base?: I): Diagnostics {
    return Diagnostics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Diagnostics>, I>>(object: I): Diagnostics {
    const message = createBaseDiagnostics();
    message.hardwareVersion = object.hardwareVersion ?? "";
    message.softwareVersion = object.softwareVersion ?? "";
    message.firmwareVersion = object.firmwareVersion ?? "";
    message.cpuUsage = object.cpuUsage ?? 0;
    message.memoryUsage = object.memoryUsage ?? 0;
    message.deviceStatus = object.deviceStatus ?? 0;
    message.checksum = object.checksum ?? "";
    return message;
  },
};

function createBaseRegisterDeviceRequest(): RegisterDeviceRequest {
  return { deviceId: "", alias: "", host: "", port: 0, portGateway: 0, protocol: 0 };
}

export const RegisterDeviceRequest = {
  encode(message: RegisterDeviceRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.deviceId !== "") {
      writer.uint32(10).string(message.deviceId);
    }
    if (message.alias !== "") {
      writer.uint32(18).string(message.alias);
    }
    if (message.host !== "") {
      writer.uint32(26).string(message.host);
    }
    if (message.port !== 0) {
      writer.uint32(32).int64(message.port);
    }
    if (message.portGateway !== 0) {
      writer.uint32(40).int64(message.portGateway);
    }
    if (message.protocol !== 0) {
      writer.uint32(48).int32(message.protocol);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RegisterDeviceRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.alias = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.host = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.port = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.portGateway = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.protocol = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterDeviceRequest {
    return {
      deviceId: isSet(object.device_id) ? globalThis.String(object.device_id) : "",
      alias: isSet(object.alias) ? globalThis.String(object.alias) : "",
      host: isSet(object.host) ? globalThis.String(object.host) : "",
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
      portGateway: isSet(object.port_gateway) ? globalThis.Number(object.port_gateway) : 0,
      protocol: isSet(object.protocol) ? protocolFromJSON(object.protocol) : 0,
    };
  },

  toJSON(message: RegisterDeviceRequest): unknown {
    const obj: any = {};
    if (message.deviceId !== "") {
      obj.device_id = message.deviceId;
    }
    if (message.alias !== "") {
      obj.alias = message.alias;
    }
    if (message.host !== "") {
      obj.host = message.host;
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    if (message.portGateway !== 0) {
      obj.port_gateway = Math.round(message.portGateway);
    }
    if (message.protocol !== 0) {
      obj.protocol = protocolToJSON(message.protocol);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterDeviceRequest>, I>>(base?: I): RegisterDeviceRequest {
    return RegisterDeviceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterDeviceRequest>, I>>(object: I): RegisterDeviceRequest {
    const message = createBaseRegisterDeviceRequest();
    message.deviceId = object.deviceId ?? "";
    message.alias = object.alias ?? "";
    message.host = object.host ?? "";
    message.port = object.port ?? 0;
    message.portGateway = object.portGateway ?? 0;
    message.protocol = object.protocol ?? 0;
    return message;
  },
};

function createBaseRegisterDeviceResponse(): RegisterDeviceResponse {
  return { device: undefined };
}

export const RegisterDeviceResponse = {
  encode(message: RegisterDeviceResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.device !== undefined) {
      Device.encode(message.device, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RegisterDeviceResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterDeviceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.device = Device.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterDeviceResponse {
    return { device: isSet(object.device) ? Device.fromJSON(object.device) : undefined };
  },

  toJSON(message: RegisterDeviceResponse): unknown {
    const obj: any = {};
    if (message.device !== undefined) {
      obj.device = Device.toJSON(message.device);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterDeviceResponse>, I>>(base?: I): RegisterDeviceResponse {
    return RegisterDeviceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterDeviceResponse>, I>>(object: I): RegisterDeviceResponse {
    const message = createBaseRegisterDeviceResponse();
    message.device = (object.device !== undefined && object.device !== null)
      ? Device.fromPartial(object.device)
      : undefined;
    return message;
  },
};

function createBaseListDevicesResponse(): ListDevicesResponse {
  return { devices: [] };
}

export const ListDevicesResponse = {
  encode(message: ListDevicesResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.devices) {
      Device.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListDevicesResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDevicesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.devices.push(Device.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDevicesResponse {
    return {
      devices: globalThis.Array.isArray(object?.devices) ? object.devices.map((e: any) => Device.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListDevicesResponse): unknown {
    const obj: any = {};
    if (message.devices?.length) {
      obj.devices = message.devices.map((e) => Device.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListDevicesResponse>, I>>(base?: I): ListDevicesResponse {
    return ListDevicesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDevicesResponse>, I>>(object: I): ListDevicesResponse {
    const message = createBaseListDevicesResponse();
    message.devices = object.devices?.map((e) => Device.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateDeviceRequest(): UpdateDeviceRequest {
  return { deviceId: "", deviceStatus: 0 };
}

export const UpdateDeviceRequest = {
  encode(message: UpdateDeviceRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.deviceId !== "") {
      writer.uint32(10).string(message.deviceId);
    }
    if (message.deviceStatus !== 0) {
      writer.uint32(16).int32(message.deviceStatus);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpdateDeviceRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.deviceStatus = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateDeviceRequest {
    return {
      deviceId: isSet(object.device_id) ? globalThis.String(object.device_id) : "",
      deviceStatus: isSet(object.device_status) ? deviceStatusFromJSON(object.device_status) : 0,
    };
  },

  toJSON(message: UpdateDeviceRequest): unknown {
    const obj: any = {};
    if (message.deviceId !== "") {
      obj.device_id = message.deviceId;
    }
    if (message.deviceStatus !== 0) {
      obj.device_status = deviceStatusToJSON(message.deviceStatus);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateDeviceRequest>, I>>(base?: I): UpdateDeviceRequest {
    return UpdateDeviceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateDeviceRequest>, I>>(object: I): UpdateDeviceRequest {
    const message = createBaseUpdateDeviceRequest();
    message.deviceId = object.deviceId ?? "";
    message.deviceStatus = object.deviceStatus ?? 0;
    return message;
  },
};

function createBaseDiagnosticsRequest(): DiagnosticsRequest {
  return { deviceId: "" };
}

export const DiagnosticsRequest = {
  encode(message: DiagnosticsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.deviceId !== "") {
      writer.uint32(10).string(message.deviceId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DiagnosticsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiagnosticsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.deviceId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiagnosticsRequest {
    return { deviceId: isSet(object.device_id) ? globalThis.String(object.device_id) : "" };
  },

  toJSON(message: DiagnosticsRequest): unknown {
    const obj: any = {};
    if (message.deviceId !== "") {
      obj.device_id = message.deviceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiagnosticsRequest>, I>>(base?: I): DiagnosticsRequest {
    return DiagnosticsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiagnosticsRequest>, I>>(object: I): DiagnosticsRequest {
    const message = createBaseDiagnosticsRequest();
    message.deviceId = object.deviceId ?? "";
    return message;
  },
};

function createBaseDiagnosticsResponse(): DiagnosticsResponse {
  return { device: undefined, diagnostics: undefined, updatedAt: undefined };
}

export const DiagnosticsResponse = {
  encode(message: DiagnosticsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.device !== undefined) {
      Device.encode(message.device, writer.uint32(10).fork()).ldelim();
    }
    if (message.diagnostics !== undefined) {
      Diagnostics.encode(message.diagnostics, writer.uint32(18).fork()).ldelim();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DiagnosticsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiagnosticsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.device = Device.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.diagnostics = Diagnostics.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiagnosticsResponse {
    return {
      device: isSet(object.device) ? Device.fromJSON(object.device) : undefined,
      diagnostics: isSet(object.diagnostics) ? Diagnostics.fromJSON(object.diagnostics) : undefined,
      updatedAt: isSet(object.updated_at) ? fromJsonTimestamp(object.updated_at) : undefined,
    };
  },

  toJSON(message: DiagnosticsResponse): unknown {
    const obj: any = {};
    if (message.device !== undefined) {
      obj.device = Device.toJSON(message.device);
    }
    if (message.diagnostics !== undefined) {
      obj.diagnostics = Diagnostics.toJSON(message.diagnostics);
    }
    if (message.updatedAt !== undefined) {
      obj.updated_at = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiagnosticsResponse>, I>>(base?: I): DiagnosticsResponse {
    return DiagnosticsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiagnosticsResponse>, I>>(object: I): DiagnosticsResponse {
    const message = createBaseDiagnosticsResponse();
    message.device = (object.device !== undefined && object.device !== null)
      ? Device.fromPartial(object.device)
      : undefined;
    message.diagnostics = (object.diagnostics !== undefined && object.diagnostics !== null)
      ? Diagnostics.fromPartial(object.diagnostics)
      : undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
