/**
 * @fileoverview gRPC-Web generated client stub for monitor.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.4
// source: monitor/v1/monitor.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as monitor_v1_monitor_pb from '../../monitor/v1/monitor_pb'; // proto import: "monitor/v1/monitor.proto"


export class MonitorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetHealth = new grpcWeb.MethodDescriptor(
    '/monitor.v1.Monitor/GetHealth',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  getHealth(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  getHealth(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  getHealth(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/monitor.v1.Monitor/GetHealth',
        request,
        metadata || {},
        this.methodDescriptorGetHealth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/monitor.v1.Monitor/GetHealth',
    request,
    metadata || {},
    this.methodDescriptorGetHealth);
  }

  methodDescriptorRegisterDevice = new grpcWeb.MethodDescriptor(
    '/monitor.v1.Monitor/RegisterDevice',
    grpcWeb.MethodType.UNARY,
    monitor_v1_monitor_pb.RegisterDeviceRequest,
    monitor_v1_monitor_pb.RegisterDeviceResponse,
    (request: monitor_v1_monitor_pb.RegisterDeviceRequest) => {
      return request.serializeBinary();
    },
    monitor_v1_monitor_pb.RegisterDeviceResponse.deserializeBinary
  );

  registerDevice(
    request: monitor_v1_monitor_pb.RegisterDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<monitor_v1_monitor_pb.RegisterDeviceResponse>;

  registerDevice(
    request: monitor_v1_monitor_pb.RegisterDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: monitor_v1_monitor_pb.RegisterDeviceResponse) => void): grpcWeb.ClientReadableStream<monitor_v1_monitor_pb.RegisterDeviceResponse>;

  registerDevice(
    request: monitor_v1_monitor_pb.RegisterDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: monitor_v1_monitor_pb.RegisterDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/monitor.v1.Monitor/RegisterDevice',
        request,
        metadata || {},
        this.methodDescriptorRegisterDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/monitor.v1.Monitor/RegisterDevice',
    request,
    metadata || {},
    this.methodDescriptorRegisterDevice);
  }

  methodDescriptorListDevices = new grpcWeb.MethodDescriptor(
    '/monitor.v1.Monitor/ListDevices',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    monitor_v1_monitor_pb.ListDevicesResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    monitor_v1_monitor_pb.ListDevicesResponse.deserializeBinary
  );

  listDevices(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<monitor_v1_monitor_pb.ListDevicesResponse>;

  listDevices(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: monitor_v1_monitor_pb.ListDevicesResponse) => void): grpcWeb.ClientReadableStream<monitor_v1_monitor_pb.ListDevicesResponse>;

  listDevices(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: monitor_v1_monitor_pb.ListDevicesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/monitor.v1.Monitor/ListDevices',
        request,
        metadata || {},
        this.methodDescriptorListDevices,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/monitor.v1.Monitor/ListDevices',
    request,
    metadata || {},
    this.methodDescriptorListDevices);
  }

  methodDescriptorUpdateDevice = new grpcWeb.MethodDescriptor(
    '/monitor.v1.Monitor/UpdateDevice',
    grpcWeb.MethodType.UNARY,
    monitor_v1_monitor_pb.UpdateDeviceRequest,
    google_protobuf_empty_pb.Empty,
    (request: monitor_v1_monitor_pb.UpdateDeviceRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  updateDevice(
    request: monitor_v1_monitor_pb.UpdateDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  updateDevice(
    request: monitor_v1_monitor_pb.UpdateDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  updateDevice(
    request: monitor_v1_monitor_pb.UpdateDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/monitor.v1.Monitor/UpdateDevice',
        request,
        metadata || {},
        this.methodDescriptorUpdateDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/monitor.v1.Monitor/UpdateDevice',
    request,
    metadata || {},
    this.methodDescriptorUpdateDevice);
  }

  methodDescriptorGetDiagnostics = new grpcWeb.MethodDescriptor(
    '/monitor.v1.Monitor/GetDiagnostics',
    grpcWeb.MethodType.UNARY,
    monitor_v1_monitor_pb.DiagnosticsRequest,
    monitor_v1_monitor_pb.DiagnosticsResponse,
    (request: monitor_v1_monitor_pb.DiagnosticsRequest) => {
      return request.serializeBinary();
    },
    monitor_v1_monitor_pb.DiagnosticsResponse.deserializeBinary
  );

  getDiagnostics(
    request: monitor_v1_monitor_pb.DiagnosticsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<monitor_v1_monitor_pb.DiagnosticsResponse>;

  getDiagnostics(
    request: monitor_v1_monitor_pb.DiagnosticsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: monitor_v1_monitor_pb.DiagnosticsResponse) => void): grpcWeb.ClientReadableStream<monitor_v1_monitor_pb.DiagnosticsResponse>;

  getDiagnostics(
    request: monitor_v1_monitor_pb.DiagnosticsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: monitor_v1_monitor_pb.DiagnosticsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/monitor.v1.Monitor/GetDiagnostics',
        request,
        metadata || {},
        this.methodDescriptorGetDiagnostics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/monitor.v1.Monitor/GetDiagnostics',
    request,
    metadata || {},
    this.methodDescriptorGetDiagnostics);
  }

  methodDescriptorStreamDiagnostics = new grpcWeb.MethodDescriptor(
    '/monitor.v1.Monitor/StreamDiagnostics',
    grpcWeb.MethodType.SERVER_STREAMING,
    monitor_v1_monitor_pb.DiagnosticsRequest,
    monitor_v1_monitor_pb.DiagnosticsResponse,
    (request: monitor_v1_monitor_pb.DiagnosticsRequest) => {
      return request.serializeBinary();
    },
    monitor_v1_monitor_pb.DiagnosticsResponse.deserializeBinary
  );

  streamDiagnostics(
    request: monitor_v1_monitor_pb.DiagnosticsRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<monitor_v1_monitor_pb.DiagnosticsResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/monitor.v1.Monitor/StreamDiagnostics',
      request,
      metadata || {},
      this.methodDescriptorStreamDiagnostics);
  }

}

