// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"errors"
	"fmt"
)

const (
	// DatabasePostgres is a Database of type postgres.
	DatabasePostgres Database = "postgres"
)

var ErrInvalidDatabase = errors.New("not a valid Database")

// String implements the Stringer interface.
func (x Database) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Database) IsValid() bool {
	_, err := ParseDatabase(string(x))
	return err == nil
}

var _DatabaseValue = map[string]Database{
	"postgres": DatabasePostgres,
}

// ParseDatabase attempts to convert a string to a Database.
func ParseDatabase(name string) (Database, error) {
	if x, ok := _DatabaseValue[name]; ok {
		return x, nil
	}
	return Database(""), fmt.Errorf("%s is %w", name, ErrInvalidDatabase)
}

const (
	// DatabaseInstanceUbiquiti is a DatabaseInstance of type ubiquiti.
	DatabaseInstanceUbiquiti DatabaseInstance = "ubiquiti"
)

var ErrInvalidDatabaseInstance = errors.New("not a valid DatabaseInstance")

// String implements the Stringer interface.
func (x DatabaseInstance) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DatabaseInstance) IsValid() bool {
	_, err := ParseDatabaseInstance(string(x))
	return err == nil
}

var _DatabaseInstanceValue = map[string]DatabaseInstance{
	"ubiquiti": DatabaseInstanceUbiquiti,
}

// ParseDatabaseInstance attempts to convert a string to a DatabaseInstance.
func ParseDatabaseInstance(name string) (DatabaseInstance, error) {
	if x, ok := _DatabaseInstanceValue[name]; ok {
		return x, nil
	}
	return DatabaseInstance(""), fmt.Errorf("%s is %w", name, ErrInvalidDatabaseInstance)
}

const (
	// EnvironmentTest is a Environment of type test.
	EnvironmentTest Environment = "test"
	// EnvironmentDevelopment is a Environment of type development.
	EnvironmentDevelopment Environment = "development"
	// EnvironmentStaging is a Environment of type staging.
	EnvironmentStaging Environment = "staging"
	// EnvironmentProduction is a Environment of type production.
	EnvironmentProduction Environment = "production"
)

var ErrInvalidEnvironment = errors.New("not a valid Environment")

// String implements the Stringer interface.
func (x Environment) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Environment) IsValid() bool {
	_, err := ParseEnvironment(string(x))
	return err == nil
}

var _EnvironmentValue = map[string]Environment{
	"test":        EnvironmentTest,
	"development": EnvironmentDevelopment,
	"staging":     EnvironmentStaging,
	"production":  EnvironmentProduction,
}

// ParseEnvironment attempts to convert a string to a Environment.
func ParseEnvironment(name string) (Environment, error) {
	if x, ok := _EnvironmentValue[name]; ok {
		return x, nil
	}
	return Environment(""), fmt.Errorf("%s is %w", name, ErrInvalidEnvironment)
}

const (
	// PostgresConnectionProxy is a PostgresConnection of type proxy.
	PostgresConnectionProxy PostgresConnection = "proxy"
	// PostgresConnectionInstance is a PostgresConnection of type instance.
	PostgresConnectionInstance PostgresConnection = "instance"
)

var ErrInvalidPostgresConnection = errors.New("not a valid PostgresConnection")

// String implements the Stringer interface.
func (x PostgresConnection) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PostgresConnection) IsValid() bool {
	_, err := ParsePostgresConnection(string(x))
	return err == nil
}

var _PostgresConnectionValue = map[string]PostgresConnection{
	"proxy":    PostgresConnectionProxy,
	"instance": PostgresConnectionInstance,
}

// ParsePostgresConnection attempts to convert a string to a PostgresConnection.
func ParsePostgresConnection(name string) (PostgresConnection, error) {
	if x, ok := _PostgresConnectionValue[name]; ok {
		return x, nil
	}
	return PostgresConnection(""), fmt.Errorf("%s is %w", name, ErrInvalidPostgresConnection)
}
