// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"errors"
	"fmt"
)

const (
	// DatabasePostgres is a Database of type postgres.
	DatabasePostgres Database = "postgres"
)

var ErrInvalidDatabase = errors.New("not a valid Database")

// String implements the Stringer interface.
func (x Database) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Database) IsValid() bool {
	_, err := ParseDatabase(string(x))
	return err == nil
}

var _DatabaseValue = map[string]Database{
	"postgres": DatabasePostgres,
}

// ParseDatabase attempts to convert a string to a Database.
func ParseDatabase(name string) (Database, error) {
	if x, ok := _DatabaseValue[name]; ok {
		return x, nil
	}
	return Database(""), fmt.Errorf("%s is %w", name, ErrInvalidDatabase)
}

const (
	// DatabaseInstanceUbiquiti is a DatabaseInstance of type ubiquiti.
	DatabaseInstanceUbiquiti DatabaseInstance = "ubiquiti"
)

var ErrInvalidDatabaseInstance = errors.New("not a valid DatabaseInstance")

// String implements the Stringer interface.
func (x DatabaseInstance) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DatabaseInstance) IsValid() bool {
	_, err := ParseDatabaseInstance(string(x))
	return err == nil
}

var _DatabaseInstanceValue = map[string]DatabaseInstance{
	"ubiquiti": DatabaseInstanceUbiquiti,
}

// ParseDatabaseInstance attempts to convert a string to a DatabaseInstance.
func ParseDatabaseInstance(name string) (DatabaseInstance, error) {
	if x, ok := _DatabaseInstanceValue[name]; ok {
		return x, nil
	}
	return DatabaseInstance(""), fmt.Errorf("%s is %w", name, ErrInvalidDatabaseInstance)
}

const (
	// DeviceStatusHealthy is a DeviceStatus of type healthy.
	DeviceStatusHealthy DeviceStatus = "DEVICE_STATUS_HEALTHY"
	// DeviceStatusDegraded is a DeviceStatus of type degraded.
	DeviceStatusDegraded DeviceStatus = "DEVICE_STATUS_DEGRADED"
	// DeviceStatusError is a DeviceStatus of type error.
	DeviceStatusError DeviceStatus = "DEVICE_STATUS_ERROR"
	// DeviceStatusMaintenance is a DeviceStatus of type maintenance.
	DeviceStatusMaintenance DeviceStatus = "DEVICE_STATUS_MAINTENANCE"
	// DeviceStatusBooting is a DeviceStatus of type booting.
	DeviceStatusBooting DeviceStatus = "DEVICE_STATUS_BOOTING"
	// DeviceStatusOffline is a DeviceStatus of type offline.
	DeviceStatusOffline DeviceStatus = "DEVICE_STATUS_OFFLINE"
)

var ErrInvalidDeviceStatus = errors.New("not a valid DeviceStatus")

// String implements the Stringer interface.
func (x DeviceStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeviceStatus) IsValid() bool {
	_, err := ParseDeviceStatus(string(x))
	return err == nil
}

var _DeviceStatusValue = map[string]DeviceStatus{
	"DEVICE_STATUS_HEALTHY":     DeviceStatusHealthy,
	"DEVICE_STATUS_DEGRADED":    DeviceStatusDegraded,
	"DEVICE_STATUS_ERROR":       DeviceStatusError,
	"DEVICE_STATUS_MAINTENANCE": DeviceStatusMaintenance,
	"DEVICE_STATUS_BOOTING":     DeviceStatusBooting,
	"DEVICE_STATUS_OFFLINE":     DeviceStatusOffline,
}

// ParseDeviceStatus attempts to convert a string to a DeviceStatus.
func ParseDeviceStatus(name string) (DeviceStatus, error) {
	if x, ok := _DeviceStatusValue[name]; ok {
		return x, nil
	}
	return DeviceStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDeviceStatus)
}

const (
	// EnvironmentTest is a Environment of type test.
	EnvironmentTest Environment = "test"
	// EnvironmentDevelopment is a Environment of type development.
	EnvironmentDevelopment Environment = "development"
	// EnvironmentStaging is a Environment of type staging.
	EnvironmentStaging Environment = "staging"
	// EnvironmentProduction is a Environment of type production.
	EnvironmentProduction Environment = "production"
)

var ErrInvalidEnvironment = errors.New("not a valid Environment")

// String implements the Stringer interface.
func (x Environment) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Environment) IsValid() bool {
	_, err := ParseEnvironment(string(x))
	return err == nil
}

var _EnvironmentValue = map[string]Environment{
	"test":        EnvironmentTest,
	"development": EnvironmentDevelopment,
	"staging":     EnvironmentStaging,
	"production":  EnvironmentProduction,
}

// ParseEnvironment attempts to convert a string to a Environment.
func ParseEnvironment(name string) (Environment, error) {
	if x, ok := _EnvironmentValue[name]; ok {
		return x, nil
	}
	return Environment(""), fmt.Errorf("%s is %w", name, ErrInvalidEnvironment)
}

const (
	// PostgresConnectionProxy is a PostgresConnection of type proxy.
	PostgresConnectionProxy PostgresConnection = "proxy"
)

var ErrInvalidPostgresConnection = errors.New("not a valid PostgresConnection")

// String implements the Stringer interface.
func (x PostgresConnection) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PostgresConnection) IsValid() bool {
	_, err := ParsePostgresConnection(string(x))
	return err == nil
}

var _PostgresConnectionValue = map[string]PostgresConnection{
	"proxy": PostgresConnectionProxy,
}

// ParsePostgresConnection attempts to convert a string to a PostgresConnection.
func ParsePostgresConnection(name string) (PostgresConnection, error) {
	if x, ok := _PostgresConnectionValue[name]; ok {
		return x, nil
	}
	return PostgresConnection(""), fmt.Errorf("%s is %w", name, ErrInvalidPostgresConnection)
}

const (
	// ProtocolHttp is a Protocol of type http.
	ProtocolHttp Protocol = "PROTOCOL_HTTP"
	// ProtocolHttpStream is a Protocol of type http-stream.
	ProtocolHttpStream Protocol = "PROTOCOL_HTTP_STREAM"
	// ProtocolGrpc is a Protocol of type grpc.
	ProtocolGrpc Protocol = "PROTOCOL_GRPC"
	// ProtocolGrpcStream is a Protocol of type grpc-stream.
	ProtocolGrpcStream Protocol = "PROTOCOL_GRPC_STREAM"
)

var ErrInvalidProtocol = errors.New("not a valid Protocol")

// String implements the Stringer interface.
func (x Protocol) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Protocol) IsValid() bool {
	_, err := ParseProtocol(string(x))
	return err == nil
}

var _ProtocolValue = map[string]Protocol{
	"PROTOCOL_HTTP":        ProtocolHttp,
	"PROTOCOL_HTTP_STREAM": ProtocolHttpStream,
	"PROTOCOL_GRPC":        ProtocolGrpc,
	"PROTOCOL_GRPC_STREAM": ProtocolGrpcStream,
}

// ParseProtocol attempts to convert a string to a Protocol.
func ParseProtocol(name string) (Protocol, error) {
	if x, ok := _ProtocolValue[name]; ok {
		return x, nil
	}
	return Protocol(""), fmt.Errorf("%s is %w", name, ErrInvalidProtocol)
}
