// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"errors"
	"fmt"
)

const (
	// DeviceStatusHealthy is a DeviceStatus of type healthy.
	DeviceStatusHealthy DeviceStatus = "DEVICE_STATUS_HEALTHY"
	// DeviceStatusDegraded is a DeviceStatus of type degraded.
	DeviceStatusDegraded DeviceStatus = "DEVICE_STATUS_DEGRADED"
	// DeviceStatusError is a DeviceStatus of type error.
	DeviceStatusError DeviceStatus = "DEVICE_STATUS_ERROR"
	// DeviceStatusMaintenance is a DeviceStatus of type maintenance.
	DeviceStatusMaintenance DeviceStatus = "DEVICE_STATUS_MAINTENANCE"
	// DeviceStatusBooting is a DeviceStatus of type booting.
	DeviceStatusBooting DeviceStatus = "DEVICE_STATUS_BOOTING"
)

var ErrInvalidDeviceStatus = errors.New("not a valid DeviceStatus")

// String implements the Stringer interface.
func (x DeviceStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeviceStatus) IsValid() bool {
	_, err := ParseDeviceStatus(string(x))
	return err == nil
}

var _DeviceStatusValue = map[string]DeviceStatus{
	"DEVICE_STATUS_HEALTHY":     DeviceStatusHealthy,
	"DEVICE_STATUS_DEGRADED":    DeviceStatusDegraded,
	"DEVICE_STATUS_ERROR":       DeviceStatusError,
	"DEVICE_STATUS_MAINTENANCE": DeviceStatusMaintenance,
	"DEVICE_STATUS_BOOTING":     DeviceStatusBooting,
}

// ParseDeviceStatus attempts to convert a string to a DeviceStatus.
func ParseDeviceStatus(name string) (DeviceStatus, error) {
	if x, ok := _DeviceStatusValue[name]; ok {
		return x, nil
	}
	return DeviceStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDeviceStatus)
}

const (
	// EnvironmentTest is a Environment of type test.
	EnvironmentTest Environment = "test"
	// EnvironmentDevelopment is a Environment of type development.
	EnvironmentDevelopment Environment = "development"
	// EnvironmentStaging is a Environment of type staging.
	EnvironmentStaging Environment = "staging"
	// EnvironmentProduction is a Environment of type production.
	EnvironmentProduction Environment = "production"
)

var ErrInvalidEnvironment = errors.New("not a valid Environment")

// String implements the Stringer interface.
func (x Environment) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Environment) IsValid() bool {
	_, err := ParseEnvironment(string(x))
	return err == nil
}

var _EnvironmentValue = map[string]Environment{
	"test":        EnvironmentTest,
	"development": EnvironmentDevelopment,
	"staging":     EnvironmentStaging,
	"production":  EnvironmentProduction,
}

// ParseEnvironment attempts to convert a string to a Environment.
func ParseEnvironment(name string) (Environment, error) {
	if x, ok := _EnvironmentValue[name]; ok {
		return x, nil
	}
	return Environment(""), fmt.Errorf("%s is %w", name, ErrInvalidEnvironment)
}

const (
	// ProtocolHttp is a Protocol of type http.
	ProtocolHttp Protocol = "http"
	// ProtocolGrpc is a Protocol of type grpc.
	ProtocolGrpc Protocol = "grpc"
)

var ErrInvalidProtocol = errors.New("not a valid Protocol")

// String implements the Stringer interface.
func (x Protocol) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Protocol) IsValid() bool {
	_, err := ParseProtocol(string(x))
	return err == nil
}

var _ProtocolValue = map[string]Protocol{
	"http": ProtocolHttp,
	"grpc": ProtocolGrpc,
}

// ParseProtocol attempts to convert a string to a Protocol.
func ParseProtocol(name string) (Protocol, error) {
	if x, ok := _ProtocolValue[name]; ok {
		return x, nil
	}
	return Protocol(""), fmt.Errorf("%s is %w", name, ErrInvalidProtocol)
}
