// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: proto/device/v1/device.proto

package devicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_HEALTHY     DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_DEGRADED    DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_ERROR       DeviceStatus = 3
	DeviceStatus_DEVICE_STATUS_MAINTENANCE DeviceStatus = 4
	DeviceStatus_DEVICE_STATUS_BOOTING     DeviceStatus = 5
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_HEALTHY",
		2: "DEVICE_STATUS_DEGRADED",
		3: "DEVICE_STATUS_ERROR",
		4: "DEVICE_STATUS_MAINTENANCE",
		5: "DEVICE_STATUS_BOOTING",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED": 0,
		"DEVICE_STATUS_HEALTHY":     1,
		"DEVICE_STATUS_DEGRADED":    2,
		"DEVICE_STATUS_ERROR":       3,
		"DEVICE_STATUS_MAINTENANCE": 4,
		"DEVICE_STATUS_BOOTING":     5,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_device_v1_device_proto_enumTypes[0].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_proto_device_v1_device_proto_enumTypes[0]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{0}
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_proto_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{0}
}

type GetHealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SupportedProtocols []string               `protobuf:"bytes,3,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	Architecture       string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Os                 string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_proto_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetHealthResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetHealthResponse) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *GetHealthResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetHealthResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type GetDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsRequest) Reset() {
	*x = GetDiagnosticsRequest{}
	mi := &file_proto_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsRequest) ProtoMessage() {}

func (x *GetDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{2}
}

type DiagnosticsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceId        string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,3,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,4,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,5,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     float64                `protobuf:"fixed64,7,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DeviceStatus    DeviceStatus           `protobuf:"varint,8,opt,name=device_status,json=deviceStatus,proto3,enum=device.v1.DeviceStatus" json:"device_status,omitempty"`
	Checksum        string                 `protobuf:"bytes,9,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagnosticsResponse) Reset() {
	*x = DiagnosticsResponse{}
	mi := &file_proto_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResponse) ProtoMessage() {}

func (x *DiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*DiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *DiagnosticsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DiagnosticsResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DiagnosticsResponse) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *DiagnosticsResponse) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *DiagnosticsResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *DiagnosticsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *DiagnosticsResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *DiagnosticsResponse) GetDeviceStatus() DeviceStatus {
	if x != nil {
		return x.DeviceStatus
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *DiagnosticsResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type UpdateDeviceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceStatus  DeviceStatus           `protobuf:"varint,2,opt,name=device_status,json=deviceStatus,proto3,enum=device.v1.DeviceStatus" json:"device_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceStateRequest) Reset() {
	*x = UpdateDeviceStateRequest{}
	mi := &file_proto_device_v1_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceStateRequest) ProtoMessage() {}

func (x *UpdateDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDeviceStateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateDeviceStateRequest) GetDeviceStatus() DeviceStatus {
	if x != nil {
		return x.DeviceStatus
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

type UpdateDeviceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceStateResponse) Reset() {
	*x = UpdateDeviceStateResponse{}
	mi := &file_proto_device_v1_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceStateResponse) ProtoMessage() {}

func (x *UpdateDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{5}
}

var File_proto_device_v1_device_proto protoreflect.FileDescriptor

const file_proto_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/device/v1/device.proto\x12\tdevice.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10GetHealthRequest\"\xcf\x01\n" +
	"\x11GetHealthResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12/\n" +
	"\x13supported_protocols\x18\x03 \x03(\tR\x12supportedProtocols\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\"\x17\n" +
	"\x15GetDiagnosticsRequest\"\x87\x03\n" +
	"\x13DiagnosticsResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12)\n" +
	"\x10hardware_version\x18\x03 \x01(\tR\x0fhardwareVersion\x12)\n" +
	"\x10software_version\x18\x04 \x01(\tR\x0fsoftwareVersion\x12)\n" +
	"\x10firmware_version\x18\x05 \x01(\tR\x0ffirmwareVersion\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\a \x01(\x01R\vmemoryUsage\x12<\n" +
	"\rdevice_status\x18\b \x01(\x0e2\x17.device.v1.DeviceStatusR\fdeviceStatus\x12\x1a\n" +
	"\bchecksum\x18\t \x01(\tR\bchecksum\"u\n" +
	"\x18UpdateDeviceStateRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12<\n" +
	"\rdevice_status\x18\x02 \x01(\x0e2\x17.device.v1.DeviceStatusR\fdeviceStatus\"\x1b\n" +
	"\x19UpdateDeviceStateResponse*\xb7\x01\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DEVICE_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16DEVICE_STATUS_DEGRADED\x10\x02\x12\x17\n" +
	"\x13DEVICE_STATUS_ERROR\x10\x03\x12\x1d\n" +
	"\x19DEVICE_STATUS_MAINTENANCE\x10\x04\x12\x19\n" +
	"\x15DEVICE_STATUS_BOOTING\x10\x052\xc7\x03\n" +
	"\x06Device\x12Z\n" +
	"\tGetHealth\x12\x1b.device.v1.GetHealthRequest\x1a\x1c.device.v1.GetHealthResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12k\n" +
	"\x0eGetDiagnostics\x12 .device.v1.GetDiagnosticsRequest\x1a\x1e.device.v1.DiagnosticsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/diagnostics\x12w\n" +
	"\x11StreamDiagnostics\x12 .device.v1.GetDiagnosticsRequest\x1a\x1e.device.v1.DiagnosticsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/diagnostics/stream0\x01\x12{\n" +
	"\x11UpdateDeviceState\x12#.device.v1.UpdateDeviceStateRequest\x1a$.device.v1.UpdateDeviceStateResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*2\x10/v1/device/stateBCZAgithub.com/emil-j-olsson/ubiquiti/device/proto/device/v1;devicev1b\x06proto3"

var (
	file_proto_device_v1_device_proto_rawDescOnce sync.Once
	file_proto_device_v1_device_proto_rawDescData []byte
)

func file_proto_device_v1_device_proto_rawDescGZIP() []byte {
	file_proto_device_v1_device_proto_rawDescOnce.Do(func() {
		file_proto_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_device_v1_device_proto_rawDesc), len(file_proto_device_v1_device_proto_rawDesc)))
	})
	return file_proto_device_v1_device_proto_rawDescData
}

var file_proto_device_v1_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_device_v1_device_proto_goTypes = []any{
	(DeviceStatus)(0),                 // 0: device.v1.DeviceStatus
	(*GetHealthRequest)(nil),          // 1: device.v1.GetHealthRequest
	(*GetHealthResponse)(nil),         // 2: device.v1.GetHealthResponse
	(*GetDiagnosticsRequest)(nil),     // 3: device.v1.GetDiagnosticsRequest
	(*DiagnosticsResponse)(nil),       // 4: device.v1.DiagnosticsResponse
	(*UpdateDeviceStateRequest)(nil),  // 5: device.v1.UpdateDeviceStateRequest
	(*UpdateDeviceStateResponse)(nil), // 6: device.v1.UpdateDeviceStateResponse
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
}
var file_proto_device_v1_device_proto_depIdxs = []int32{
	7, // 0: device.v1.GetHealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	7, // 1: device.v1.DiagnosticsResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: device.v1.DiagnosticsResponse.device_status:type_name -> device.v1.DeviceStatus
	0, // 3: device.v1.UpdateDeviceStateRequest.device_status:type_name -> device.v1.DeviceStatus
	1, // 4: device.v1.Device.GetHealth:input_type -> device.v1.GetHealthRequest
	3, // 5: device.v1.Device.GetDiagnostics:input_type -> device.v1.GetDiagnosticsRequest
	3, // 6: device.v1.Device.StreamDiagnostics:input_type -> device.v1.GetDiagnosticsRequest
	5, // 7: device.v1.Device.UpdateDeviceState:input_type -> device.v1.UpdateDeviceStateRequest
	2, // 8: device.v1.Device.GetHealth:output_type -> device.v1.GetHealthResponse
	4, // 9: device.v1.Device.GetDiagnostics:output_type -> device.v1.DiagnosticsResponse
	4, // 10: device.v1.Device.StreamDiagnostics:output_type -> device.v1.DiagnosticsResponse
	6, // 11: device.v1.Device.UpdateDeviceState:output_type -> device.v1.UpdateDeviceStateResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_device_v1_device_proto_init() }
func file_proto_device_v1_device_proto_init() {
	if File_proto_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_device_v1_device_proto_rawDesc), len(file_proto_device_v1_device_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_v1_device_proto_goTypes,
		DependencyIndexes: file_proto_device_v1_device_proto_depIdxs,
		EnumInfos:         file_proto_device_v1_device_proto_enumTypes,
		MessageInfos:      file_proto_device_v1_device_proto_msgTypes,
	}.Build()
	File_proto_device_v1_device_proto = out.File
	file_proto_device_v1_device_proto_goTypes = nil
	file_proto_device_v1_device_proto_depIdxs = nil
}
