// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: proto/device/v1/device.proto

package devicev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_HTTP        Protocol = 1
	Protocol_PROTOCOL_HTTP_STREAM Protocol = 2
	Protocol_PROTOCOL_GRPC        Protocol = 3
	Protocol_PROTOCOL_GRPC_STREAM Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_HTTP",
		2: "PROTOCOL_HTTP_STREAM",
		3: "PROTOCOL_GRPC",
		4: "PROTOCOL_GRPC_STREAM",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_HTTP":        1,
		"PROTOCOL_HTTP_STREAM": 2,
		"PROTOCOL_GRPC":        3,
		"PROTOCOL_GRPC_STREAM": 4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_device_v1_device_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_device_v1_device_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{0}
}

type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_HEALTHY     DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_DEGRADED    DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_ERROR       DeviceStatus = 3
	DeviceStatus_DEVICE_STATUS_MAINTENANCE DeviceStatus = 4
	DeviceStatus_DEVICE_STATUS_BOOTING     DeviceStatus = 5
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_HEALTHY",
		2: "DEVICE_STATUS_DEGRADED",
		3: "DEVICE_STATUS_ERROR",
		4: "DEVICE_STATUS_MAINTENANCE",
		5: "DEVICE_STATUS_BOOTING",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED": 0,
		"DEVICE_STATUS_HEALTHY":     1,
		"DEVICE_STATUS_DEGRADED":    2,
		"DEVICE_STATUS_ERROR":       3,
		"DEVICE_STATUS_MAINTENANCE": 4,
		"DEVICE_STATUS_BOOTING":     5,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_device_v1_device_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_proto_device_v1_device_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{1}
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_proto_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{0}
}

type GetHealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,proto3" json:"device_id,omitempty"`
	SupportedProtocols []Protocol             `protobuf:"varint,3,rep,packed,name=supported_protocols,proto3,enum=device.v1.Protocol" json:"supported_protocols,omitempty"`
	Architecture       string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Os                 string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_proto_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetHealthResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetHealthResponse) GetSupportedProtocols() []Protocol {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *GetHealthResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetHealthResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type DiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticsRequest) Reset() {
	*x = DiagnosticsRequest{}
	mi := &file_proto_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsRequest) ProtoMessage() {}

func (x *DiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*DiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{2}
}

type DiagnosticsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceId        string                 `protobuf:"bytes,2,opt,name=device_id,proto3" json:"device_id,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,3,opt,name=hardware_version,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,4,opt,name=software_version,proto3" json:"software_version,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,5,opt,name=firmware_version,proto3" json:"firmware_version,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,6,opt,name=cpu_usage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     float64                `protobuf:"fixed64,7,opt,name=memory_usage,proto3" json:"memory_usage,omitempty"`
	DeviceStatus    DeviceStatus           `protobuf:"varint,8,opt,name=device_status,proto3,enum=device.v1.DeviceStatus" json:"device_status,omitempty"`
	Checksum        string                 `protobuf:"bytes,9,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagnosticsResponse) Reset() {
	*x = DiagnosticsResponse{}
	mi := &file_proto_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResponse) ProtoMessage() {}

func (x *DiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*DiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{3}
}

func (x *DiagnosticsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DiagnosticsResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DiagnosticsResponse) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *DiagnosticsResponse) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *DiagnosticsResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *DiagnosticsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *DiagnosticsResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *DiagnosticsResponse) GetDeviceStatus() DeviceStatus {
	if x != nil {
		return x.DeviceStatus
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *DiagnosticsResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceStatus  DeviceStatus           `protobuf:"varint,1,opt,name=device_status,proto3,enum=device.v1.DeviceStatus" json:"device_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_proto_device_v1_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDeviceRequest) GetDeviceStatus() DeviceStatus {
	if x != nil {
		return x.DeviceStatus
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_proto_device_v1_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_v1_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_v1_device_proto_rawDescGZIP(), []int{5}
}

var File_proto_device_v1_device_proto protoreflect.FileDescriptor

const file_proto_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/device/v1/device.proto\x12\tdevice.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10GetHealthRequest\"\xe8\x01\n" +
	"\x11GetHealthResponse\x12:\n" +
	"\n" +
	"updated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x12\x1c\n" +
	"\tdevice_id\x18\x02 \x01(\tR\tdevice_id\x12E\n" +
	"\x13supported_protocols\x18\x03 \x03(\x0e2\x13.device.v1.ProtocolR\x13supported_protocols\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\"\x14\n" +
	"\x12DiagnosticsRequest\"\x8e\x03\n" +
	"\x13DiagnosticsResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tdevice_id\x18\x02 \x01(\tR\tdevice_id\x12*\n" +
	"\x10hardware_version\x18\x03 \x01(\tR\x10hardware_version\x12*\n" +
	"\x10software_version\x18\x04 \x01(\tR\x10software_version\x12*\n" +
	"\x10firmware_version\x18\x05 \x01(\tR\x10firmware_version\x12\x1c\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\tcpu_usage\x12\"\n" +
	"\fmemory_usage\x18\a \x01(\x01R\fmemory_usage\x12=\n" +
	"\rdevice_status\x18\b \x01(\x0e2\x17.device.v1.DeviceStatusR\rdevice_status\x12\x1a\n" +
	"\bchecksum\x18\t \x01(\tR\bchecksum\"T\n" +
	"\x13UpdateDeviceRequest\x12=\n" +
	"\rdevice_status\x18\x01 \x01(\x0e2\x17.device.v1.DeviceStatusR\rdevice_status\"\x16\n" +
	"\x14UpdateDeviceResponse*~\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPROTOCOL_HTTP\x10\x01\x12\x18\n" +
	"\x14PROTOCOL_HTTP_STREAM\x10\x02\x12\x11\n" +
	"\rPROTOCOL_GRPC\x10\x03\x12\x18\n" +
	"\x14PROTOCOL_GRPC_STREAM\x10\x04*\xb7\x01\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DEVICE_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16DEVICE_STATUS_DEGRADED\x10\x02\x12\x17\n" +
	"\x13DEVICE_STATUS_ERROR\x10\x03\x12\x1d\n" +
	"\x19DEVICE_STATUS_MAINTENANCE\x10\x04\x12\x19\n" +
	"\x15DEVICE_STATUS_BOOTING\x10\x052\xac\x03\n" +
	"\x06Device\x12Z\n" +
	"\tGetHealth\x12\x1b.device.v1.GetHealthRequest\x1a\x1c.device.v1.GetHealthResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12h\n" +
	"\x0eGetDiagnostics\x12\x1d.device.v1.DiagnosticsRequest\x1a\x1e.device.v1.DiagnosticsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/diagnostics\x12t\n" +
	"\x11StreamDiagnostics\x12\x1d.device.v1.DiagnosticsRequest\x1a\x1e.device.v1.DiagnosticsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/diagnostics/stream0\x01\x12f\n" +
	"\fUpdateDevice\x12\x1e.device.v1.UpdateDeviceRequest\x1a\x1f.device.v1.UpdateDeviceResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*2\n" +
	"/v1/deviceBCZAgithub.com/emil-j-olsson/ubiquiti/device/proto/device/v1;devicev1b\x06proto3"

var (
	file_proto_device_v1_device_proto_rawDescOnce sync.Once
	file_proto_device_v1_device_proto_rawDescData []byte
)

func file_proto_device_v1_device_proto_rawDescGZIP() []byte {
	file_proto_device_v1_device_proto_rawDescOnce.Do(func() {
		file_proto_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_device_v1_device_proto_rawDesc), len(file_proto_device_v1_device_proto_rawDesc)))
	})
	return file_proto_device_v1_device_proto_rawDescData
}

var file_proto_device_v1_device_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_device_v1_device_proto_goTypes = []any{
	(Protocol)(0),                 // 0: device.v1.Protocol
	(DeviceStatus)(0),             // 1: device.v1.DeviceStatus
	(*GetHealthRequest)(nil),      // 2: device.v1.GetHealthRequest
	(*GetHealthResponse)(nil),     // 3: device.v1.GetHealthResponse
	(*DiagnosticsRequest)(nil),    // 4: device.v1.DiagnosticsRequest
	(*DiagnosticsResponse)(nil),   // 5: device.v1.DiagnosticsResponse
	(*UpdateDeviceRequest)(nil),   // 6: device.v1.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil),  // 7: device.v1.UpdateDeviceResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_device_v1_device_proto_depIdxs = []int32{
	8, // 0: device.v1.GetHealthResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: device.v1.GetHealthResponse.supported_protocols:type_name -> device.v1.Protocol
	8, // 2: device.v1.DiagnosticsResponse.timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: device.v1.DiagnosticsResponse.device_status:type_name -> device.v1.DeviceStatus
	1, // 4: device.v1.UpdateDeviceRequest.device_status:type_name -> device.v1.DeviceStatus
	2, // 5: device.v1.Device.GetHealth:input_type -> device.v1.GetHealthRequest
	4, // 6: device.v1.Device.GetDiagnostics:input_type -> device.v1.DiagnosticsRequest
	4, // 7: device.v1.Device.StreamDiagnostics:input_type -> device.v1.DiagnosticsRequest
	6, // 8: device.v1.Device.UpdateDevice:input_type -> device.v1.UpdateDeviceRequest
	3, // 9: device.v1.Device.GetHealth:output_type -> device.v1.GetHealthResponse
	5, // 10: device.v1.Device.GetDiagnostics:output_type -> device.v1.DiagnosticsResponse
	5, // 11: device.v1.Device.StreamDiagnostics:output_type -> device.v1.DiagnosticsResponse
	7, // 12: device.v1.Device.UpdateDevice:output_type -> device.v1.UpdateDeviceResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_device_v1_device_proto_init() }
func file_proto_device_v1_device_proto_init() {
	if File_proto_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_device_v1_device_proto_rawDesc), len(file_proto_device_v1_device_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_v1_device_proto_goTypes,
		DependencyIndexes: file_proto_device_v1_device_proto_depIdxs,
		EnumInfos:         file_proto_device_v1_device_proto_enumTypes,
		MessageInfos:      file_proto_device_v1_device_proto_msgTypes,
	}.Build()
	File_proto_device_v1_device_proto = out.File
	file_proto_device_v1_device_proto_goTypes = nil
	file_proto_device_v1_device_proto_depIdxs = nil
}
