// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: proto/monitor/v1/monitor.proto

package monitorv1

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_proto_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/monitor/v1/monitor.proto\x12\n" +
	"monitor.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto2Z\n" +
	"\aMonitor\x12O\n" +
	"\tGetHealth\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/healthBFZDgithub.com/emil-j-olsson/ubiquiti/backend/proto/monitor/v1;monitorv1b\x06proto3"

var file_proto_monitor_v1_monitor_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_proto_monitor_v1_monitor_proto_depIdxs = []int32{
	0, // 0: monitor.v1.Monitor.GetHealth:input_type -> google.protobuf.Empty
	0, // 1: monitor.v1.Monitor.GetHealth:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_monitor_v1_monitor_proto_init() }
func file_proto_monitor_v1_monitor_proto_init() {
	if File_proto_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitor_v1_monitor_proto_rawDesc), len(file_proto_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_proto_monitor_v1_monitor_proto_depIdxs,
	}.Build()
	File_proto_monitor_v1_monitor_proto = out.File
	file_proto_monitor_v1_monitor_proto_goTypes = nil
	file_proto_monitor_v1_monitor_proto_depIdxs = nil
}
