// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package fixtures

import (
	"errors"
	"fmt"
)

const (
	// ProtocolHttp is a Protocol of type http.
	ProtocolHttp Protocol = "PROTOCOL_HTTP"
	// ProtocolHttpStream is a Protocol of type http-stream.
	ProtocolHttpStream Protocol = "PROTOCOL_HTTP_STREAM"
	// ProtocolGrpc is a Protocol of type grpc.
	ProtocolGrpc Protocol = "PROTOCOL_GRPC"
	// ProtocolGrpcStream is a Protocol of type grpc-stream.
	ProtocolGrpcStream Protocol = "PROTOCOL_GRPC_STREAM"
)

var ErrInvalidProtocol = errors.New("not a valid Protocol")

// String implements the Stringer interface.
func (x Protocol) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Protocol) IsValid() bool {
	_, err := ParseProtocol(string(x))
	return err == nil
}

var _ProtocolValue = map[string]Protocol{
	"PROTOCOL_HTTP":        ProtocolHttp,
	"PROTOCOL_HTTP_STREAM": ProtocolHttpStream,
	"PROTOCOL_GRPC":        ProtocolGrpc,
	"PROTOCOL_GRPC_STREAM": ProtocolGrpcStream,
}

// ParseProtocol attempts to convert a string to a Protocol.
func ParseProtocol(name string) (Protocol, error) {
	if x, ok := _ProtocolValue[name]; ok {
		return x, nil
	}
	return Protocol(""), fmt.Errorf("%s is %w", name, ErrInvalidProtocol)
}

const (
	// ServiceDeviceRouter is a Service of type device-router.
	ServiceDeviceRouter Service = "device-router"
	// ServiceDeviceSwitch is a Service of type device-switch.
	ServiceDeviceSwitch Service = "device-switch"
	// ServiceDeviceAccessPoint is a Service of type device-access-point.
	ServiceDeviceAccessPoint Service = "device-access-point"
	// ServiceBackendMonitorArm is a Service of type backend-monitor-arm.
	ServiceBackendMonitorArm Service = "backend-monitor-arm"
	// ServiceBackendMonitorAmd is a Service of type backend-monitor-amd.
	ServiceBackendMonitorAmd Service = "backend-monitor-amd"
	// ServiceInvalid is a Service of type invalid.
	ServiceInvalid Service = "invalid"
)

var ErrInvalidService = errors.New("not a valid Service")

// String implements the Stringer interface.
func (x Service) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Service) IsValid() bool {
	_, err := ParseService(string(x))
	return err == nil
}

var _ServiceValue = map[string]Service{
	"device-router":       ServiceDeviceRouter,
	"device-switch":       ServiceDeviceSwitch,
	"device-access-point": ServiceDeviceAccessPoint,
	"backend-monitor-arm": ServiceBackendMonitorArm,
	"backend-monitor-amd": ServiceBackendMonitorAmd,
	"invalid":             ServiceInvalid,
}

// ParseService attempts to convert a string to a Service.
func ParseService(name string) (Service, error) {
	if x, ok := _ServiceValue[name]; ok {
		return x, nil
	}
	return Service(""), fmt.Errorf("%s is %w", name, ErrInvalidService)
}
